### ISSUE TITLE
Path to configuration files cannot be set

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#104]
Since update of context for language, the "Path to configuration files" no longer works
<img width="324" alt="Screenshot_1591468221" src="https://user-images.githubusercontent.com/2428217/83951849-e6abb580-a834-11ea-93ab-41e9787e3c48.png">

I tested back the commits and it was working with my pull request of 31 may: https://github.com/Sentaroh/SMBSync2/pull/99

I quickly looked at it and did not see why. Log is not helpful. I tried a few fixes but did not work

Best regards

**Comment by Sentaroh** [comment]
Thank you.

Sorry, I forgot to add setting_mgt_dir to checkSettingValue().

Best regards.

**Comment by PhilZ-cwm6** [comment]
np, thank you, it is fixed now
