### ISSUE TITLE
Feature request: Scheduler retry on failed / missed tasks

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#114]
I just noticed that missed/failed sync tasks started by scheduler are not retried until next schedule
Also, if we are in Settings, the scheduled event won't start and will be delayed until next planned schedule.

This is annoying for daily SMB schedules, if NAS or Wifi were not available. It will be even worse for longer schedule plans like weekly...

I tried to look at it and started implementing the basic preferences part: https://github.com/PhilZ-cwm6/SMBSync2/tree/patch_schdeduler_preview

However, while following the code, I see that there is no return or join between the Sync Request Item when passed to Sync Thread by syncRequestQueue() and the demanding Sync Schedule Item.

I renounced to continue modifying the code as it will be important changes in your sources+ it will take me some time to follow the source and understand the code

Hope you can add an option in the Scheduler to retry these failed syncs, with a user choice: time interval in minutes + number of retries, exp. retry every 30mn for 3 times

Thank you and best regards

**Comment by PhilZ-cwm6** [comment]
Just thought at a simpler approach: add option directly in Sync Task instead of the schedule plan:
- simpler to implement
- if Schedule plan contains more than one sync task, only the failed sync task is repeated
- if sync task is manually started: it will also repeat

Failed sync task can create a schedule event to repeat, like a queue, in the main schedule window

**Comment by Sentaroh** [comment]
Thank you.

I don't understand why I need to retry when a scheduled sync is terminated with an error.
1.The retry will not succeed if the PC is asleep when you schedule a synchronization at home while you are asleep.
2.When you are out of the house, you will not be able to connect, so the retry will not succeed (except for VPN connection).
3.You can manually resynchronize if the synchronization is terminated in error, leaving a notification. (Except when you hide it in the settings.)

Best regards.

**Comment by PhilZ-cwm6** [comment]
Yes, good point of view, that's what I do actually,
Just for the feedback and if you ever think again about it, I started editing the code with this logic:
- auto create a schedule for failed sync tasks (done)
- add extra schedule flag for retry number
- add extra schedule flag for delete schedule plan after num retries
- add extra sync task flag to not auto add the retried sync task to new schedules
- queue would appear in the bottom of existing Schedule TAB with name like: Retry_syncTaskName_yyyymmdd_hhmmss.msec

I close the issue since it is not that important as you noted
Best regards
