### ISSUE TITLE
Landscape vs Large issue before API 26

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#118]
Hi,
I noticed a few weeks ago that in Settings, the override built in device Land vs Large layout doesn't work properly in anything before API 26. It causes a back stack like issue you can see when:
- Enter Settings in Portrait mode
- Turn to landscape: pans are not shown
- Click an entry: pan is shown

or
- Enter Settings in Portrait mode
- Click an entry: like UI settings
- Turn to landscape: pans are not shown

This was not bothering

However, now, on one of my old devices I noticed it is also in Messages: the Large/Land layout is never applied

I tested in Emulator
**Nexus 6 API 25 and before:**
<img width="768" alt="Screenshot_1592566769" src="https://user-images.githubusercontent.com/2428217/85129843-1a72dc00-b234-11ea-854b-f6ba5413ea4a.png">

**Nexus 6 API 26 and later**
<img width="768" alt="Screenshot_1592566883" src="https://user-images.githubusercontent.com/2428217/85129905-3c6c5e80-b234-11ea-885e-19040a183cc0.png">

I tried to debug it a bit in Settings:
onIsMultiPane() is properly overridden and entered, but the effect is partial and provokes the back stack like issue. It is not only related to the "Force Tablet Mode" but also to the isTablet() changed based on language. Anything changing the device built in value for onIsMultiPane() causes the issue pre-API 26

Do you have an idea why it is like that ?

**Comment by PhilZ-cwm6** [comment]
It can be fixed when starting app in Landscape directly
Broken if app is started in Landscape

Seems like an issue when restoring config change view in the code, affecting API 25 and before !

**Comment by PhilZ-cwm6** [comment]
Same for all views in fact, from Main App:

Start app in portrait, turn to land:
<img width="768" alt="Screenshot_1592575149" src="https://user-images.githubusercontent.com/2428217/85140731-f5876480-b245-11ea-9c53-20acc01d3536.png">

Start app in Land directly
<img width="768" alt="Screenshot_1592575161" src="https://user-images.githubusercontent.com/2428217/85140735-f61ffb00-b245-11ea-8b57-fced1fe10393.png">

Start app in Land and turn device in Portrait: Land view persists !
<img width="432" alt="Screenshot_1592575270" src="https://user-images.githubusercontent.com/2428217/85140883-38493c80-b246-11ea-9099-a2978c32a2a3.png">

**Comment by Sentaroh** [comment]
For some reason, Configuration does not seem to be stored in the Activity.
I added the following code to onConfigurationChanged()

if (Build.VERSION.SDK_INT<26) mActivity.getResources().updateConfiguration(newConfig, mActivity.getResources().getDisplayMetrics());

Best regards.

**Comment by PhilZ-cwm6** [comment]
It is properly fixed in MainActivity views
Settings Activity not fixed, but it is not disturbing. In Settings, in landscape, with UI submenu displayed, when rotate from land to portrait, it is back to the main Settings menu instead of the currently selected UI Settings view.

But I don't think anyone will notice it

Best regards
