### ISSUE TITLE
Potential issue: Language not changed in Play release APK

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#119]
Please, check this thread if you have issues with switching language when you publish the APK in PLAY:
https://github.com/YarikSOffice/lingver/issues/27
and
https://stackoverflow.com/questions/52731670/android-app-bundle-with-in-app-locale-change

I think the code changes in build.gradle are needed

If user has device in Russian only and app has Russian XML, it will be fixed to Russian and crash in English as I understand it. It is impossible to test since it is related to Play bundle

Close the issue if you are aware of it, I forgot to mention it when pushed the language changes

Best regards

**Comment by Sentaroh** [comment]
Thank you.

SMBSync2 doesn't use the App Bundle, so I don't think that's a problem.
However, until Google forces the App Bundle.

Best regards.
