### ISSUE TITLE
Official SMBSync2 Exclude / Include filters behavior and issues #96 (Continued)

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#123]
This continues the https://github.com/Sentaroh/SMBSync2/issues/96 issue

I hope we got a winner: pushed the patch to the current filters v2 commit
**Please check attached java sample class method to quickly test the code and all the filter possibilities**
Any fixes should be easier to do in the sample before adapt in main code

```
Whole dir prefix: match anywhere in path
- Exclude any folder named dir: `\dir`
- Exclude all `dir1/dir2`folders: `\dir1/dir2`
- Include ANY folder named dir: not allowed, the overhead is just huge and all code in SyncThread.java, Copyfile.java, archive and zip must be rewritten

Traverse Exclude filter (no sense in include filter)
dir1/dir2   -> do not traverse dir2 (empty dir2 not created)
dir1/dir2/   -> traverse dir2 (empty dir2 created)
\dir and \dir/   -> same as above to traverse or not

All other Include and Exclude filters behavior is identical between filters
The below combinations are allowed and act as expected also with Whole dir prefix `\`
cache   -> master/cache/*
/cache   -> master/cache/*
cache*   -> master/cache*/
*cache  -> master/*cache
/cache/data   -> master/cache/data/*
/cache/data/   -> master/cache/data/*
cache/data   -> master/cache/data/*
cache/data*   -> master/cache/data*

Wildcard ? matches ONE char
dir?/dir5   -> master/dirX/dir5

Wildcard * will match any char up to the next dir separator "/" char
dir*/dir2   -> master/dirxxxx/dir2
*/dir    -> master/oneDirLevel/dir
dir1/*/dir2   -> master/dir1/oneDirLevel/dir2
dir/*   -> master/dir/oneDirLevel
```

**Attached code class sample to fully test and if needed fix the exclude matcher code: rename to .java**
Old version: [sample.java.txt](https://github.com/Sentaroh/SMBSync2/files/4853997/sample.java.txt)
New version: 2 posts below

**Comment by PhilZ-cwm6** [comment]
Please test the sample java code snippet also and look at it for any code optimization or fix if needed

**Comment by PhilZ-cwm6** [comment]
still a few small bugs to fix in final, not the sample, will commit in a moment

**Comment by PhilZ-cwm6** [comment]
Updated final unless bugs are found:
- overhead optimized at the max in loops
- fixed small bug fix caused by copy/paste from sample.java in optimize speed code: properly check next filters after first did not match because of optimized loop break
- I kept the whole dir prefix and non whole dir prefix with asterisk parts separated by if/else (redundant code) mainly for readability and code maintenance since it also doesn't affect performance.
- `dir/*` is now also matched against the array and `*` is considered one level if alone in a path: exclude or include `dir/*` will not match files inside dir folder, but only directories
- filters guide in post 1 updated


Best regards

**Comment by PhilZ-cwm6** [comment]
With the last tightened overhead performance: [sample.java.txt](https://github.com/Sentaroh/SMBSync2/files/4856511/sample.java.txt)

**Comment by PhilZ-cwm6** [comment]
I tested the inlcude filters and the isDirectorySelectedByDirectoryNameVer2() include pattern matcher is fine because it is a second pass

**With the last tightened overhead performance:** [sample.java.txt](https://github.com/Sentaroh/SMBSync2/files/4856511/sample.java.txt)


Best regards

**Comment by PhilZ-cwm6** [comment]
I changed isDirectorySelectedByDirectoryNameVer2() to use **INCLUDE** filter by array also. It is really wired to have it match `*` filters wrongly in the background. Code is wrong like it was with the exclude, just not apparent. Would fail a direct call by an eventual other method.

No need to optimize the overhead: Pattern Matcher does a char by char compare any way and we must check from the beginning without resetting the loop like Exclude. So no real loss in speed there.

Well, hopefully I am done with the filters.

Note: Include Pattern is not used anymore, but I kept it as it doesn't slow the sync

best regards

**Comment by PhilZ-cwm6** [comment]
Just pushed a new pull request on separate branch for unexpected file deletes in the Mirror modes
I am holding my commits until my previous patches are merged

No hurry and best regards

**Comment by PhilZ-cwm6** [comment]
I reviewed the sync Mirror code:
In addition to the Unexpected File deletes in all Mirror Sync modes, there is an inconsistent issue in deleting target folders in **Mirror From Internal/External to External** mode. Mirror from/to SMB and To Internal storage are not affected by the unexpected directory deletes

Hope you can merge all my pending pull requests once they are tested so that I can commit the feature for a real perfect Mirror option. I don't want to push many changes if they won't be merged as it is a new recode time...
Let me know if any bugs

Thank you and Best regards

**Comment by Sentaroh** [comment]
Sorry for late response.

Please allow a couple of days for us to review and test your changes.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Sure, no problem
It is important that you review and fully test it before, even if it takes a few weeks before enabling the option

I will also test time in the loop: I think the pattern matcher can be removed in exclude also, leaving only the array matcher for both include and exclude. Pattern matcher source uses a char by char check, so I don't expect it much faster than the array by array pattern compare. If the overhead is marginal, I will remove it and commit: less code lines -> less bugs -> less maintenance

Best regards

**Comment by PhilZ-cwm6** [comment]
Thank you for the merge, I hope longer tests will show no bug. I am rather confident.

I pushed a new pull request to remove the dirExcludeFilterPatternList. It contains a debug commit with a timer to monitor time spent in the filters during sync. The overhead is really marginal, about 370 msec for a 3:50 mn sync (< 0.1%) with 1200 files.
We would need a nanosecond clock to monitor finely, which is ridiculous because most hardware doesn't have a nanosec clock precision and results are not reliable.

Also, in all my tests, the array matcher is always faster (30-40 msec, so a 10%) probably because of the optimized code breaking the loop when filter is longer than the path to filter. So, paradoxically, the longest is the filter, the faster it will be compared to pattern matcher !

Your code is also optimized to not recurse into excluded folders.

So, the dirExcludeFilterPatternListhas no more reason to exist. The dirIncludeFilterPatternList was already removed

Best regards

**Comment by PhilZ-cwm6** [comment]
I just pushed my probably last major contribution to your project. I will take a break for the next couple of months at least.
I hope you merge the 2 pending requests

I think the sync code is now bug free after these. I will monitor SMBSync3 and I hope you can merge the changes easily without too much bugs in the sync code mainly.

Thank you again for all your work and mainly the involvement in migrating it to Android R

Best regards

PS: I will still be able to push small fixes if needed, just not major features

**Comment by PhilZ-cwm6** [comment]
updated with a bug fix I overlooked
Rebased properly at the same time
Best regards

**Comment by PhilZ-cwm6** [comment]
I completed the pull request with:
- Notify the GUI that `Mirror `mode is changed to `Mirror (Exact Image)`, display it in Warning colour in Main app screen and as ÌMAGE`
- fix the ZIP Mirror was not respecting filters and hidden dirs/files options during deletes

**Comment by Sentaroh** [comment]
Thank you.

Testing has begun. Please wait a couple of days for the results.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Thank you for this great follow up

**Comment by PhilZ-cwm6** [comment]
Hi,
I am a bit disappointed because this part was a really big work. The current filters is really broken with unpredicted deletes in some circumstances. The new filter v2 is just bug free, more featured and much better optimized for speed over remote SMB

For me it is not a big problem because I can compile my own version. But, I like for some devices having the Play version, which I cannot now because of the filters.

Hope you enable it in release version, even if it is not the default for compatibility

Best regards

**Comment by Sentaroh** [comment]
Hi,

I forgot to enable it. I've just pushed it.

Best regards.

**Comment by PhilZ-cwm6** [comment]
oh, that's nice, thank you very much
