### ISSUE TITLE
Master -> Source

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#125]
If you are aware of this news:
https://www.bbc.com/news/technology-53050955

Maybe it is a good idea in SMBSync3 before its release to rename Master -> Source
For French, it is same thing: "Source" instead of "Maître"
Would make it future proof is Play also chooses to ban these in next years (many users could do also...)

Best regards

**Comment by Sentaroh** [comment]
Thank you.

I will change from Master/Target to Source/Destination.

Best regards.
