### ISSUE TITLE
Wired display in Settings Context Menu

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#129]
Hi,

The last build (after the last Utilities change ?), when compiled, gives me this on my Galaxy Note 4 Android M device

<img width="299" alt="Screenshot_2020-07-10-22-47-48" src="https://user-images.githubusercontent.com/2428217/87203927-fa4eae00-c303-11ea-901e-2ff6a51b297a.png">

Problem is that I cannot reproduce it on any of my other devices and also not in the emulator. Closing + kill app did not fix it.
I uninstalled SMBSync2, reinstalled + restored my settings, the problem is gone and I can no longer reproduce it.

Just to let you know if it tells you something...

**Comment by Sentaroh** [comment]
Thank you.

I tested it with Sony Xperia (Android 6) and Emulator but could not reproduce it.
I've been developing this since Android 2.3, but this is the first time I've seen this happen.

Best regards.

**Comment by PhilZ-cwm6** [comment]
I close as i cannot reproduce it too
