### ISSUE TITLE
Warning about the Exact image mode

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#131]
Hi,

The option "Maintain Target directory as an exact image of the Source (Mirror mode only)" is really valuable to get rid of temp/cache/thumb files in the target for example

I understand your choice to remove the "Image" and "(Exact Image)" GUI hacks to avoid confusion.

However, maybe it is a good idea to add a message like the "filter_select_edit_msg", in Warning theme color (yellow), when user enters the dir/file filters dialog while that option is enabled. Button Ok would be enabled, but just a text warning on top for example ?
Something like: `Caution: "Maintain Target directory as an exact image of the Source option" is enabled`

I let you decide and add it if you think it is good

Best regards

**Comment by Sentaroh** [comment]
A warning message is now displayed.
![image](https://user-images.githubusercontent.com/4037866/87887486-b0cb3500-ca60-11ea-8bc4-e096f43da1f6.png)

Best regards.

**Comment by PhilZ-cwm6** [comment]
yes, it looks good, just pushed a cleanup in the code part
