### ISSUE TITLE
Nightly signed release (non debug apk) 

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#134]
Hi,
Now that filters are fixed, I am going to post it in an xda and phoneandroid threads. 

What do you think about adding a release-nightly-apk, like the debug-apk, signed like in app store, for people that would like to install latest commits but di not know how to compile it ? That way it also doesn't break the Play updates like with debug.

Best regards

**Comment by Sentaroh** [comment]
Hi,

We are not going to release the pre-release APKs because we think it will be difficult to deal with any problems that may arise with the features under testing.

We will add a link to the published APK in the README.txt file.

Best regards.
