### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#142]
Hi,

Here are 3 pics with the different layouts of the new main view:

**Current new layout (NonWordWrap):**
<img width="324" alt="Screenshot_1595769742" src="https://user-images.githubusercontent.com/2428217/88480136-80016900-cf54-11ea-935b-066a727ea181.png">

**Here's with a simple WordWrap TextView**
<img width="324" alt="Screenshot_1595769592" src="https://user-images.githubusercontent.com/2428217/88480138-8099ff80-cf54-11ea-857a-4a3e63a17c75.png">

**And with an ellipSize="middle"**
<img width="324" alt="Screenshot_1595769647" src="https://user-images.githubusercontent.com/2428217/88480139-81329600-cf54-11ea-8c09-babf3580e9fa.png">

1) NonWordWrap is really barely readable and eyes tiring for the main app GUI that user first gets on opening
2) WordWrap paths are perfectly readable, less eye tiring but it is really less nice aesthetically than 1) and 3)
3) Single Line with middle Ellipse: readable, main info is present (start and end) and really good aesthetically for the main App GUI facing the user. No eye tiring effect also with the text

Would you consider like you suggested in my old request to use option 3), without the dynamic size change you did not like: that is simply revert to `TextView`, `singleLine="true"` and ellipsize= "middle" in the xml ?

**Note**:
In Edit Sync Task, the spacing, contrast and button layout makes it readable and nice looking in NonWordWrap:
This is really ok:
<img width="324" alt="Screenshot_1595770741" src="https://user-images.githubusercontent.com/2428217/88480487-6f51f280-cf56-11ea-8dc7-6b46dffce1a3.png">

**Comment by Sentaroh** [comment]
Thank you.

I used 2.32-fix-test to push.

Best regards.

**Comment by PhilZ-cwm6** [comment]
- main view task list layout: Yeh, it looks nice now and still functional
I did not think at "lines=1" instead of deprecated "singleLine". I tested and it also works when programatically changing the lines, preserving the ellipsize=middle, unlike MaxLines

- Warning colors: it is really better and more pro again now

- arrow icon: I tested layout in multiline and it is perfect

**Note**: please try to not add many warning dialogs in the future. Else, each action and test will be cluttered with the confirmation dialogs. Maybe an option in the future to disable the Warning dialogs, but keep the Dangerous ones ? It can also be an option active only during the session, disabled on restart ? Or a third button in warning dialogs with "Do not ask again during this session" ?

I keep this open for a few days until you are done with the GUI.

Best regards

**Comment by Sentaroh** [comment]
Hi,

The dialog is shown to the user to explain when an action is required and why there is an error. (Toast is shown if possible)
I'm going to continue to keep the dialogue to a minimum.

Best regards.
