### ISSUE TITLE
color warning

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#145]
Hi,
While the idea is not bad, I think the colors are not really matched / assorted for the Warning
It can be ok maybe on some serious warnings, but not for regular messages like "Exit without saving..."

<img width="270" alt="Screenshot_1595797567" src="https://user-images.githubusercontent.com/2428217/88489506-e1492c80-cf94-11ea-8bc8-211cbd21516e.png">

<img width="270" alt="Screenshot_1595797197" src="https://user-images.githubusercontent.com/2428217/88489505-e017ff80-cf94-11ea-918f-8c28411e0198.png">

<img width="270" alt="Screenshot_1595797972" src="https://user-images.githubusercontent.com/2428217/88489631-a398d380-cf95-11ea-91bb-770ab543eebd.png">

The Danger dialog is ok because it is occasional and warning. But not the regular warning dialogs with many colours in a small dialog and not well matching

Just my thoughts because the app had a rather sober and pro look which doesn't match well with the warning dialogs mixing
Maybe it is enough for most warnings to just use the classic text color ?

Thank you and best regards

**Comment by Sentaroh** [comment]
Thank you.

I think the dialog message is enough of a warning.
The warning has been changed to the normal text color.

Best regards.
