### ISSUE TITLE
layout errors

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#150]
**Landscape** orientation still broken in test branch:
- week number/long/day to fix like in large
- margins and layout not consistent: if we change storage type (Internal vs SMB like below), display is changed and margins are not aligned once left, and once right

<img width="576" alt="Screenshot_1597834857" src="https://user-images.githubusercontent.com/2428217/90627996-1dcb1980-e21d-11ea-9a93-0d6c7ef207fa.png">

<img width="576" alt="Screenshot_1597834862" src="https://user-images.githubusercontent.com/2428217/90627994-1c99ec80-e21d-11ea-9076-4d5233752f0d.png">

best regards

**Comment by Sentaroh** [comment]
If you put them horizontally, they cannot be aligned with each other due to differences in the number of characters in different languages, so we put them vertically.

![image](https://user-images.githubusercontent.com/4037866/90755547-310de000-e316-11ea-84ae-113f0a15ce7e.png)

Best regards.

**Comment by PhilZ-cwm6** [comment]
I understand, it is ok for me as you did
Thank you and best regards
