### ISSUE TITLE
Icon Suggestion

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#154]
About the new icon change:
Just a few ideas, if you plan to revert to an icon in the future (Auto text in yellow is not a great esthetic effect I find)

<img width="324" alt="Screenshot_1598184093" src="https://user-images.githubusercontent.com/2428217/90978017-9e09bb80-e54a-11ea-9e18-5988cb2ad741.png">

<img width="324" alt="Screenshot_1598184422" src="https://user-images.githubusercontent.com/2428217/90978018-9f3ae880-e54a-11ea-910f-d60568bdaa3b.png">

png:
![smbsync_auto_task](https://user-images.githubusercontent.com/2428217/90978022-a9f57d80-e54a-11ea-813c-e8ce4aea021f.png)
![smbsync_auto_task_light](https://user-images.githubusercontent.com/2428217/90978023-aa8e1400-e54a-11ea-9cf9-45d8e907ae13.png)

I can provide PSP canvas if you ever need, but it is just you current ic_32_sync.png with letter A and same color as the arrow (a dark grey tint for the light)

You'll maybe have a better idea/design

Best regards

**Comment by Sentaroh** [comment]
Thank you.

The following is used in the sense of "synchronized execution", which I do not agree with, as your ICON could be mistaken for synchronized execution.
![ic_32_sync](https://user-images.githubusercontent.com/4037866/90994107-8f76df00-e5f2-11ea-951f-eb278a727b95.png)

I changed the text color of ICON.
![image](https://user-images.githubusercontent.com/4037866/90994093-7837f180-e5f2-11ea-9122-655f06216fcc.png)

Best regards.

**Comment by PhilZ-cwm6** [comment]
yes, much better now
best regards
