### ISSUE TITLE
Various bugs related to List separator

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#157]
- **Sync task list with comma in name:**
Sync task is ok, but if you add it to Schedule plan, the Scheduler cannot handle it:

<img width="270" alt="Screenshot_1598480565" src="https://user-images.githubusercontent.com/2428217/91611857-7072a700-e97c-11ea-97ff-ae0eec292e7a.png">

- **Same issue for Schedule name, if it contains ","**
The schedule name is broken and the schedule will not start

**Fix possibilities**
1. use pipe char as separator for the String holding the schedule names list and the sync tasks lists:
```
// Constants.java
public final static String SMBSYNC2_LIST_SEPARATOR="|"; //pipe char !

//in code:
String[] stl=si.syncTaskList.split(Pattern.quote(SMBSYNC2_LIST_SEPARATOR));
```
2. or use an Array List like with the Wifi AP White List
3. or do not allow "," char in sync task list name and in schedule name

For SMBSync3, I think it is better to go with fix 2

For SMBSync2, I did a quick fix that works perfectly, but 2 things need to be implemented:
- a new buildScheduleListV6 to save the new settings on first app launch after update
- external app script needs to use the new separator !

So I did not continue on it because I am not sure if you prefer to just disable "," for SMBSync2

Hope you can fix it for SMBSync3 properly using Array (or at least the ";" separator instead of the commonly used ",") and maybe for now just disable "," in the name of Schedule and Task List

Best regards

**Comment by Sentaroh** [comment]
Thank you.

In my opinion, it probably doesn't use "," in the task name, so I choose case 3.(SMBSync2 and SMBSync3)
>do not allow "," char in sync task list name and in schedule name

I'll fix it in a couple of days.

Best regards.

**Comment by PhilZ-cwm6** [comment]
yes, it is the simpler/quicker, it is ok for me
Just for the info, I shared the patch I started and abandoned. It works perfectly for the Sync Task List part. I did not fix the Schedule names, saving to v6 and the external script support

**There is also a simple way to make it completely transparent for users on update, even with external scripts:** change separator to "pipe" or ";" **but keep external scripts with "," when they are imported in SyncService.java part**. It will not support scripts with "," in task name, like now by the way ! So All users won't notice any change, except on import of tasks with "," in name (which are broken already in schedule). So only people with comma in sync task name within a schedule will notice the fix

You can even define SMBSYNC2_LIST_SEPARATOR = "," to not change anything, while being able to do in future.

Just to share since I had written it, when ever you want/have time for a cleaner approach. But again, for me you can go the simpler way if you do not have time

Best regards

**Comment by Sentaroh** [comment]
Thank you.

To interface with external applications, the task list should be separated by ",".

Best regards.
