### ISSUE TITLE
using formatted=false

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#159]
Hi,
I noticed since a few months that you are adding the `formatted=false` to silent the lint warning when 2 `%s` are in the same string. exp `task could not be found by schedule. task name=%s, schedule=%s`

Is there a reason you do not use the proper fix which is: `task could not be found by schedule. task name=%1s, schedule=%2s` ?

Here's a simple explanation:
https://www.thedroidsonroids.com/blog/android-strings-xml-tips-tricks

For now, it seems that Android allows the formatter to format the string when the `formatted=false` is present. But this could cause issues in anytime things are fixed by google. Since it is done on runtime, this would break the app in any such updated Android version

Best regards

**Comment by Sentaroh** [comment]
Thank you.

The reason is that we just followed Lint's warning.

We will not fix all messages at once, but will fix them individually in future message fixes.

Best regards.
