### ISSUE TITLE
bugs in sync task name and schedule name

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#161]
Hi,

I pushed a patch fixing some bugs introduced by your last commit that broke some checks in Sync tasks
I also fixed that renaming sync tasks and schedules could be done using invalid chars, duplicates or empty names

**Before:**
- Schedule 1 has empty name !
<img width="270" alt="Screenshot_1599159955" src="https://user-images.githubusercontent.com/2428217/92181171-f5603380-ee48-11ea-9cdc-d7f030c8e391.png">

- Two tasks with same name possible !
<img width="270" alt="Screenshot_1599160020" src="https://user-images.githubusercontent.com/2428217/92181174-f6916080-ee48-11ea-8d50-47700ef24e26.png">

- Sync task 1 has empty name !
<img width="270" alt="Screenshot_1599160028" src="https://user-images.githubusercontent.com/2428217/92181175-f6916080-ee48-11ea-89fc-147818f53772.png">

**After:**
- notify of errors in sync tasks
<img width="270" alt="Screenshot_1599169707" src="https://user-images.githubusercontent.com/2428217/92181315-3c4e2900-ee49-11ea-9d6d-28d097dbfecb.png">

- do not allow saving existing tasks by editing them
<img width="270" alt="Screenshot_1599169995" src="https://user-images.githubusercontent.com/2428217/92181319-3d7f5600-ee49-11ea-90f6-f1c78292e6a0.png">
<img width="270" alt="Screenshot_1599170002" src="https://user-images.githubusercontent.com/2428217/92181320-3d7f5600-ee49-11ea-9781-a2cf677fff0e.png">

- fix renaming of schedule and task names
<img width="270" alt="Screenshot_1599173881" src="https://user-images.githubusercontent.com/2428217/92181597-e75ee280-ee49-11ea-8b4a-75f46f696701.png">
<img width="270" alt="Screenshot_1599173892" src="https://user-images.githubusercontent.com/2428217/92181599-e7f77900-ee49-11ea-8cd0-90535d329665.png">
<img width="270" alt="Screenshot_1599173927" src="https://user-images.githubusercontent.com/2428217/92181601-e8900f80-ee49-11ea-885e-e210c482eada.png">

**Comment by PhilZ-cwm6** [comment]
**Edit: fixed in last commit**
~~To fix:~~

~~If some task names are invalid, we should set the sti.isSyncTaskError to true to disable AutoSync and sync selected~~

~~Currently, with my patch, I disable the sync button for tasks~~
~~But the below situation, Top Sync Button will AutoSync despite first task has no name at all (empty name)~~

<img width="270" alt="Screenshot_1599169707" src="https://user-images.githubusercontent.com/2428217/92181315-3c4e2900-ee49-11ea-9d6d-28d097dbfecb.png">

~~I can hide it too, but not sure if hiding top sync button is enough (call by external scripts), so I think sti.isSyncTaskError should be set~~

~~I let you decide and fix that part as you think it is better: disable topsync button if invalid tasks selected or in Auto vs set the task sti.isSyncTaskError so that external scripts do not start the bad task name~~

Best regards

**Comment by PhilZ-cwm6** [comment]
**Commit: Fix main tabs notification message for schedule errors…**

**Before:**
<img width="270" alt="Screenshot_1599203416" src="https://user-images.githubusercontent.com/2428217/92225860-1f930f00-eea4-11ea-8ecb-0cdcdee71a3f.png">

**After:**

- Detailed log with all schedules and tasks having an error:
<img width="755" alt="Untitled" src="https://user-images.githubusercontent.com/2428217/92225897-27eb4a00-eea4-11ea-9b7d-c4838e26af70.png">

- display all invalid tasks in editor
<img width="270" alt="Screenshot_1599203624" src="https://user-images.githubusercontent.com/2428217/92225890-26ba1d00-eea4-11ea-96c2-6ea664275474.png">

- show a  generic message in main tabs
<img width="324" alt="Screenshot_1599210972" src="https://user-images.githubusercontent.com/2428217/92225895-2752b380-eea4-11ea-8a68-3987da85ea61.png">

<img width="270" alt="Screenshot_1599210976" src="https://user-images.githubusercontent.com/2428217/92225891-2752b380-eea4-11ea-8ea0-a997e24ac88b.png">

**Comment by PhilZ-cwm6** [comment]
**Commit: Fix schedule error message not always refreshed**
- Notification error is refreshed when schedules are disabled individually or globally

<img width="324" alt="Screenshot_1599213985" src="https://user-images.githubusercontent.com/2428217/92229616-09884d00-eeaa-11ea-94fa-4cb65de3e1af.png">
<img width="324" alt="Screenshot_1599213994" src="https://user-images.githubusercontent.com/2428217/92229621-0a20e380-eeaa-11ea-9098-c8ae45f58534.png">

**Comment by PhilZ-cwm6** [comment]
It is now proper and bug free

Remains only the decision:
1- Hide top sync button if a selected task name is invalid (or if one of the tasks in Auto is invalid)
or
2- Add a new parm[xx] setting to update sti.isSyncTaskError on sync task name error

**Comment by PhilZ-cwm6** [comment]
**commit: Fix duplicate sync tasks detection:**

<img width="324" alt="Screenshot_1599231529" src="https://user-images.githubusercontent.com/2428217/92253904-6a2a8080-eed0-11ea-99ba-a6bb6d79ce8d.png">

- properly loads all tasks in settings so that we can edit/fix them and not keep them not accessible in settings
- display error sync task names for duplicates and non valid chars

**Comment by PhilZ-cwm6** [comment]
**Commit: properly set Sync Tasks with invalid name as erroring:**

<img width="324" alt="Screenshot_1599236350" src="https://user-images.githubusercontent.com/2428217/92263171-7c122080-eedc-11ea-8ca2-e5e36ccd6bb2.png">

This completes all the fixes properly, without needing to save to settings files
If task name is not valid (duplicate, invalid char...), sync task is now error and will not be started by Top Sync button (in AUto or Select modes), by schedules, external scripts...

Let me know if any bugs are present

Best regards

**Comment by PhilZ-cwm6** [comment]
**Commit: Fix bug where duplicate schedules by name case could be created**

- fix type
<img width="324" alt="Screenshot_1599248764" src="https://user-images.githubusercontent.com/2428217/92285875-be9c2300-ef05-11ea-894a-e7b3e76e494d.png">

- fix display and creation of schedule duplicates by case name
<img width="324" alt="Screenshot_1599254110" src="https://user-images.githubusercontent.com/2428217/92285876-bf34b980-ef05-11ea-8b83-69aeab61e397.png">

**Comment by PhilZ-cwm6** [comment]
**commit: Fix GUI bug when schedule item is deleted** 

- After a schedule item was deleted, the GUI was in a "bug" state:
bottom context buttons no more shown on item selection

<img width="324" alt="Screenshot_1599259029" src="https://user-images.githubusercontent.com/2428217/92289307-54d54680-ef10-11ea-822a-bacae06dd8f4.png">

**Comment by PhilZ-cwm6** [comment]
I am done
Will wait for merging before I continue on a small GUI aspect bugs

Best regards

**Comment by Sentaroh** [comment]
Thank you.

We have applied your changes and made some modifications.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Thank you, I missed the meaning of "EDIT"

Best regards
