### ISSUE TITLE
Properly set the sync task error state on broken sync task names

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#163]
The previous set of patches made use of mGp.syncTaskAdapter to check for duplicates and invalid chars
For invalid chars and empty sync task names, it was ok
However, for duplicates, we cannot rely on the mGp.syncTaskAdapter or the mGp.syncTaskList because they are not completely loaded on app start and on launch from SyncService

The new pull request fixes these issues and the implementation is more adequate for the duplicates.

Note: I implemented the early check in sortSyncTaskList() because it is always called on initial load of settings file + on every change to the SyncTaskList through the syncTaskAdapter.sort() call. That way, the changes are effective on the early load even without GUI and not only applied to the Adapter through GUI

I also fixed the syncTaskAdapter.sort() not called when deleting a sync task

- **Show the error message when editing a sync task with an invalid name**
<img width="324" alt="Screenshot_1599311632" src="https://user-images.githubusercontent.com/2428217/92314525-ee682b00-efd8-11ea-8ee6-b4d3cf6a09c7.png">

- **properly show error message in all cases **
also, it immediately updates the error state (+background color) when we rename/delete the task with error
<img width="324" alt="Screenshot_1599342336" src="https://user-images.githubusercontent.com/2428217/92314526-ef00c180-efd8-11ea-9dac-32e2733fe080.png">

**Comment by PhilZ-cwm6** [comment]
**commit: Allow copy of invalid sync task:**
- fixes these "COPY", "EDIT", "ADD" flags

<img width="324" alt="Screenshot_1599349470" src="https://user-images.githubusercontent.com/2428217/92315177-a221e880-efe2-11ea-8ae3-8db59877c707.png">

Now, we can also properly copy a task with invalid name if we edit the name of the new copy
I kept the `if (flags)` checks in Editor class so that the main names check method can handle it in a generic way

Let me know if there are some bugs

_Edit: even if the previous versions were not buggy and did not permit creation of invalid tasks, it is a good fix to avoid issues if user tempers with the settings files_

Thank you and best regards

**Comment by PhilZ-cwm6** [comment]
I did not have time yesterday to publish a video showing the fixes:
https://youtu.be/athIljbysfc

Note: invalid task names are created with the previous SMBSync2 version before the patches

Fixes shown:
- on app start, properly display error state for tasks with invalid names
- when task is renamed / deleted: update the error messages and the error state immeadiately
- when editing a task with error in name: show the error message not permitting to save the edited task
- when copy the task with invalid name, we can create a valid copy

Best regards

**Comment by PhilZ-cwm6** [comment]
**Commit: Set of patches for schedules:** 
- fix schedule can be renamed to an existing one
- fix duplicate schedules can be edited
- display warn info when a schedule contains tasks in error state (any error: invalid name, duplicate, invalid source/target folder...)
- always show next schedule warning when schedules has errors

<img width="324" alt="Screenshot_1599486278" src="https://user-images.githubusercontent.com/2428217/92397080-6a23be00-f126-11ea-86d9-5e0d72d4e850.png">

<img width="270" alt="Screenshot_1599491308" src="https://user-images.githubusercontent.com/2428217/92400862-e1f4e700-f12c-11ea-8a45-12ee09bd653c.png">
<img width="324" alt="Screenshot_1599491318" src="https://user-images.githubusercontent.com/2428217/92400863-e28d7d80-f12c-11ea-80cb-5d820c13a97a.png">


Best regards

**Comment by PhilZ-cwm6** [comment]
edited with latest patch pics
best regards

**Comment by PhilZ-cwm6** [comment]
**Commit: Schedule sync tasks list fixes**
- properly load all existing sync tasks in the schedule list
- properly display when a sync task is in error or not found state
- on display of the sync task list, all sync tasks defined in the schedule are set to checked so that it is easier to see the initial list
- sync tasks in error state are shown in error red color, (not found sync tasks are still in warning color)
- I did not modify the original behavior where not found/error sync tasks can be selected: user can define the schedule and fix the tasks later (useful on import schedule with broken tasks)

Before:
<img width="324" alt="Screenshot_1599514337" src="https://user-images.githubusercontent.com/2428217/92417813-7a5a8e00-f164-11ea-94e1-74b249d10186.png">

After
<img width="324" alt="Screenshot_1599514257" src="https://user-images.githubusercontent.com/2428217/92417815-7af32480-f164-11ea-8c1d-62f26669da2d.png">

**Comment by PhilZ-cwm6** [comment]
Ok, I really think the schedule stuff is fixed now

Best regards

**Comment by Sentaroh** [comment]
Thank you.

Additional fixes.
1. The task name is no longer displayed when it is blank.
2. Invalid tasks cannot be selected.
![image](https://user-images.githubusercontent.com/4037866/92426761-b2de8400-f1c5-11ea-879d-41609fbd6872.png)

Best regards.

**Comment by PhilZ-cwm6** [comment]
thank you

> Invalid tasks cannot be selected.

Exactly the idea I tried to implement but I did not find how to do it properly 👍 
best regards

**Comment by PhilZ-cwm6** [comment]
However, still there is an issue as the unckeck state cannot be saved and we can no more fix the schedule without fixing all sync tasks errors !

I will look at it, push a fix or open an issue

Best regards
