### ISSUE TITLE
Schedule sync tasks list corruption bug + Next schedule notification error bug

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#167]
Hi,

I recently found a bug that I couldn't fix in an easy way, so stopped looking at it. I was about to look at it again but I do not have much time. Hope you can look at it and fix it.

Here are the steps to reproduce:
- setup 1 or 2 sync tasks
- setup a schedule and add the sync tasks to the schedule (not Auto)
- enable the schedule
- delete or rename one of the sync tasks

Issues:
1. the sync task is also deleted/renamed in the schedule without user knowledge
It is a good feature, but should be on user decision. A prompt each time is not a good idea because you add interruptions in tasks management
   - I was planning to add a new setting (ScheduleItem.OnSyncTaskDelete for example) in the Edit Schedule dialog with a spinner:
When a Sync Task is renamed or deleted by user: 1- rename/delete the sync task in the schedule. 2- prompt for action. 3- ignore and keep the invalid task name in the schedule (will generate a warning message)
   - I did not do because of next bug

2. the Schedule TAB doesn't reflect the changes in the sync tasks list of the schedule items until a restart. Also, the Next Schedule warning is not shown if the sync task was deleted. After app restart, Schedule Tab sync list is updated

3. more annoying bug: if we do not restart app after a sync task is deleted:
   - in Schedule Tab, create a new Schedule and save it
   - restart app
   - the sync task we deleted/renamed appears now as an error in the Schedule containing it. The rename/delete was not saved in the Schedule because we created a new schedule before restarting the app

Fixes to do:
- implement a schedule item setting to "prompt"/"ignore"/"always update" the schedule sync task when  a sync task is deleted/renamed (I can add it if it can help you because of time)
- when a sync task is deleted/renamed, the Schedule Tab list should reflect the changes accordingly. If ignore is chosen by user, the next schedule warning must be updated
- the changes should be immediately saved so that they are not lost when we create a new schedule or edit an existing one before app restart

I could not find a simple way to notify the Scheduler of the changes by reloading settings from the file automatically

Hope you can look at these issues

Best regards

**Comment by Sentaroh** [comment]
Thank you.

The task renaming and deleting should be done in the following way because if it is not linked to the schedule, an error will occur that the user does not intend.
1. When you rename a task name, the task name included in the task list in the schedule is also renamed in conjunction with it.
2. When a task is deleted, the task name included in the task list in the schedule is also deleted in conjunction with it.

I'm going to alert the user in Rename and Delete Dialog.
1.Rename "When a task is renamed, the task name in the schedule is also changed."
2.Delete "When the task is deleted, the task name in the schedule is also deleted."

Bug will be fixed in a couple of days.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Hi,
Maybe just a toast notifying that the schedule was also edited. A dialog would be too annoying for repetitive rename/delete (in test and debug for example !) 
Fixing the bug where the schedule is not saved unless we restart is even enough for me.

Thank you and best regards

**Comment by PhilZ-cwm6** [comment]
Thank you,
I did not figure out that the editing was done on an in-method ScheduleList instead of the global mGp.syncTabScheduleList
Now it works

I pushed 2 commits to merge:
- properly refresh the Schedule tab when a sync task is deleted (your patch is ok on renameSyncTask)
- reapply showing the name error of a Schedule when renaming it
This is important to show errors of an existing bad schedule from previous versions (comma in name, empty or duplicate name) and to explain why the Ok button is disabled

Images of the commit fixes
- Fix deleted task not immediately shown in Schedule Tab
<img width="324" alt="Screenshot_1601284118" src="https://user-images.githubusercontent.com/2428217/94431444-98c90d80-0195-11eb-9317-28e98ece9d99.png">

- Reapply initial error message when editing a task with bad name
On first edit, "Duplicate name" is shown like with Schedules edit

<img width="324" alt="Screenshot_1599575684" src="https://user-images.githubusercontent.com/2428217/92181597-e75ee280-ee49-11ea-8b4a-75f46f696701.png">

Best regards
