### ISSUE TITLE
198.18.0.0/15 needs to be treated as private IP address block

### ISSUE THREAD

**Issue by YAMLcase** [Sentaroh/SMBSync2#169]
Please add 198.18.0.0/15 to the list of "private" IP blocks.  This is a reserved address range for benchmark testing.  This is not route-able to the internet.  Here's the RFC for your convenience: https://tools.ietf.org/html/rfc2544.  

https://tools.ietf.org/html/rfc5735 has the most up to date list of special use IPv4 Addresses which expands on the RFC 1918 ranges.  Thanks!

**Comment by PhilZ-cwm6** [comment]
Just out of curiosity,
Why would you use that specific network for your apps ? I never heard of it being used in a home/office environment and found no real info on using that domain except in the spec mentions like you linked.

Otherwise, until an official answer by dev, you can manually add the IP range you need to the white list

Best regards

**Comment by YAMLcase** [comment]
I just had to re-address my home network (10.0.0.0/16) because of conflicts with the corporate network I VPN into (10.0.0.0/8).  this is the second large company I worked for that used the same private network.  I decided to pick an address range that was the least likely to be some other corporate network I'd one day have to VPN into.  I used IANA's list of special purpose blocks to find another not well known range that has the same characteristics:

  - forwardable, but not to the internet
  - allows source and destination addresses
  - large enough for me to have several /24's

198.18/15 pretty much fits the bill, and I think the stealth factor is proving itself in this thread... neither you nor (presumably) the developer knew about it 😄 

Here's that list, it's quite useful:
https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml

**Comment by PhilZ-cwm6** [comment]
I looked at that range
Its use was preciced in rfc 6815
https://tools.ietf.org/html/rfc6815

It is intented to test/benchmark interconnection **between two different subnets**
Also note the /15 mask

I won't recommend using it outside its purpose. Consumer grade routers and devices could drop packets, or worst wrongly forward them to the internet. The specs are clear about it if you run it outside a dedicated environement

I don't think that for general use, that range should be included in the "private LAN" section

But if you want to go ahead and test, just white list the ip ranges in SMBSync2. It would have the same effect as a dedicated entry in the drop down menu

Just my opinion

Best regards

**Comment by Sentaroh** [comment]
Hi,

198.18.0.0/15 is not defined as a private address and the application cannot support it.
If you want to use 198.18.0.0/15, register it in the "IP Address List" and enable "Allow sync with all IP addresses (include public)".
![image](https://user-images.githubusercontent.com/4037866/95566519-9ea7d400-0a5c-11eb-926b-90ec159bedce.png)
Best regards.
