### ISSUE TITLE
Bug in result log file names and Sync Task Names

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#179]
Hi,

I committed a patch (https://github.com/Sentaroh/SMBSync2/pull/178) to fix the below issues.
**However, please not the following:**
- I did not add the xml msg entries, but only the english text in code to not create a merge conflict with my previous patch
- I did not fix the root cause of the GUI issue in EditSyncTask described below which needs another patch (create a new scroll view template)

I let you add the above fixes to complete the patch

Issues fixed:
- result_log txt file cannot have invalid characters else it will fail to sync to or to be saved to FAT32/NTFS or any windows system
This patch preserves the useful ability to name sync tasks freely while ensuring the result.log file is valid
We can name a task `My Main Sync Task: SDCARD -> NAS/Galaxy S20` while ensuring the log file name remains valid
Limiting the sync task name chars like FolderSync is very limiting I think and this is a good approach
- fix result_log file name length could exceed 255 chars (linux doesn't allow usually longer file names)
- ensure sync task name global length cannot be longer than 150 chars to fix a bug in the EditSyncTask GUI. Also, 150 chars seems more than enough for a sync task name

**GUI bug:**
When we rename a sync task to a very long name, the view doesn't scroll in EditSyncTask
We end up with something like this that we cannot scroll or change):
![Screenshot_1601841646](https://user-images.githubusercontent.com/2428217/95026295-9cc2c700-0690-11eb-8933-3ff9dbcf7f5e.png)

After my fix, with 150 chars limit on the Nexus S small screen:
![Screenshot_1601841736](https://user-images.githubusercontent.com/2428217/95026304-ba902c00-0690-11eb-9fd5-3c6b6a344c85.png)

So 150 chars looks like a nice spot. However, a proper fix to the scroll view is still needed

** Sync task name invalid length fix **
<img width="324" alt="Screenshot_1601841434" src="https://user-images.githubusercontent.com/2428217/95026318-d7c4fa80-0690-11eb-8566-7d8cd95d46e0.png">
<img width="324" alt="Screenshot_1601841438" src="https://user-images.githubusercontent.com/2428217/95026320-d85d9100-0690-11eb-9eea-350b0d81bc74.png">

Many thanks and best regards

**Comment by Sentaroh** [comment]
Thank you.

The number of characters in the task name will be 127 if you think about the Unicode characters, but I think 64 characters is enough for the editing screen.

Best regards.

**Comment by PhilZ-cwm6** [comment]
I am sorry
I forgot to commit the changes to CommonUtilities
Just notice it and pushed the changes that were left locally on my repo

Without it the patch was missing the main fix

best regards

**Comment by PhilZ-cwm6** [comment]
I pushed the changes I forgot and I just read your comment: It is ok for me, I let you make the changes to make it 64 chars and add the xml translations
I will fix french after it

best regards

**Comment by PhilZ-cwm6** [comment]
I made a mistake in my code here:
https://github.com/Sentaroh/SMBSync2/commit/2e9566fb446a1971258f3c7c9cf82b6a2515fe7e#diff-ac7e42ace33ae8c5f3c34ff80eb4be34R922

`if (fn.startsWith(invalid_str))`
must be replaced by
`if (fn.endsWith(invalid_str))`

In Microsoft docs, as suggested by the constant name SMBSYNC2_PROF_SYNC_LOG_FILE_INVALID_CHARS_TAIL, the file names cannot end with these chars but they can start with them

The risk is limited in your code actually because of the added date at end. However, I think it is good to keep the processing code to avoid any potential issue in the future or if the code language output changes... You are always certain that log files will never have invalid names

I let you make the change if you're ok

Best regards

**Comment by Sentaroh** [comment]
Thank you.

The file name is not directly related to the user, so let's use the Hash value of the file name.

        String dir = mGp.settingAppManagemsntDirectoryName + "/result_log";
        String dt = StringUtil.convDateTimeTo_YearMonthDayHourMinSec(System.currentTimeMillis());
        String fn = "result_" + syncProfName + "_" + dt ;
        String fn_hash=null;
        try {
            fn_hash=EncryptUtil.makeSHA1Hash(fn);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return dir + "/" + fn_hash + ".txt";


Best regards.

**Comment by PhilZ-cwm6** [comment]
It is not a good idea. Currently we can directly access the logs outside SMBSync2 to look at them on PC with a text editor. Having the sync name in log file name makes it possible to identify the log visually by name. Using a hash makes it impossible to use these logs outside your app.

**Edit:** I noticed the issue because the logs were failing to sync and i could not find them on the target smb share. 

Best regards

**Comment by Sentaroh** [comment]
Thank you.

            if (fn.endsWith(invalid_str))
The fix has been applied.

Best regards.

**Comment by PhilZ-cwm6** [comment]
thank you a lot
