### ISSUE TITLE
Add option to manually start Schedules

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#181]
Pull request: (https://github.com/Sentaroh/SMBSync2/pull/180)

Hi,

I had this patch since a few months but with inline code to parse the schedules
I finally found some time to look at the intent and clean it to use the existing timer intent code

This patch enables to start Schedules manually as I really needed that option I was used to in FolderSync and FreeFileSync

When we have a Schedule setup to run many tasks in a specified order, this can be annoying to always manually select the specified tasks when we do not want them to be set on Auto

This patch makes it possible to manually start either All Enabled Schedules or only Some Selected Schedules

**Not implemented in the patch / To do:**
- msg entries not added in xml layout: only english in-code (to not conflict with previous pull requests). The final getString from resources code is written but commented
- I did not add a dedicated intent ACTION label in the manifest, but reused the existing SCHEDULER_INTENT_TIMER_EXPIRED
I let you decide if you prefer a dedicated intent action
- I let you decide and enhance if needed the icon I quickly did for my use

Note: I am holding on any further push requests until you are done. I know you are maintaining many repos and that it is an amazing work and a lot of time

Thank you for all your work and best regards

**Comment by Sentaroh** [comment]
Thank you.

Why don't you do the following?
1. Sync button at the top of the screen shows only Task tab.
2. Display the Sync button on the schedule item
![image](https://user-images.githubusercontent.com/4037866/95073307-993e4700-0747-11eb-8cb4-b756396f8e72.png)

If you agree, I will implement it myself.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Hi,
Yes, it is a nice idea as you propose with sync button on the right of each schedule. It also makes teh GUI consistent between SyncTAB and ScheduleTAB

However, it would be great, like in SyncTab, to also have these 2 features I added in my pull request:
- top sync button to start All Enabled Schedules
- when in check mode, top sync button starts teh selected schedules

This makes it also consistent and same behavior as the SyncTab + it is really nice to start all enabled Schedules in one click + selected schedules

It would be great if you implement it as the GUI parts take me a lot of time.

Best regards

**Edit:** also, having the above mentioned 2 options like in SyncTask makes it possible to queue the tasks in the schedules instead of waiting for the schedule to finish before starting another one manually

Best regards

**Comment by Sentaroh** [comment]
Hi,

- Top Sync button is under consideration because it needs to be made other ICON to have the same meaning as Task tab.
- Queue is possible, but it will be ignored if the same task exists.

Push for Preview.

**Comment by Sentaroh** [comment]
Hi,

Change ICON.
![image](https://user-images.githubusercontent.com/4037866/95226084-7c813c80-0837-11eb-8097-0d7983e24b4f.png)

Best regards.

**Comment by PhilZ-cwm6** [comment]
In your previous version there was a bug I can no more reproduce on this new version:
Randomly, on app restart, the sync button was gone:

<img width="324" alt="Screenshot_1602007715" src="https://user-images.githubusercontent.com/2428217/95245762-dbcd5580-0813-11eb-8ece-ca0e89a221a2.png">
<img width="324" alt="Screenshot_1602007858" src="https://user-images.githubusercontent.com/2428217/95245764-dc65ec00-0813-11eb-9f3b-ae1bef387764.png">

Sometimes, on scroll, it would appear and disappear on different lines

I cannot reproduce it on the version with new icons, but I report it so that you can look at the bug if you did not fix it properly because you did not notice it (I did not have time yet to look at the code details)

Best regards

**Comment by PhilZ-cwm6** [comment]
The new layout works properly on my quick tests, thank you for the implementation
It is very convenient to have the "Start all enabled schedules" button + the select mode

**I have two things:**

- the new icons do not match well in color and aspect with your app: dark blue tone, 3D button effects and lightning effect that are all 3 absent in remaining app layouts. Maybe a more sober button to match the look of your app ?

- In your previous version there was a bug I can no more reproduce on this new version:
Randomly, on app restart, the sync button was gone:

<img width="324" alt="Screenshot_1602007715" src="https://user-images.githubusercontent.com/2428217/95245762-dbcd5580-0813-11eb-8ece-ca0e89a221a2.png">
<img width="324" alt="Screenshot_1602007858" src="https://user-images.githubusercontent.com/2428217/95245764-dc65ec00-0813-11eb-9f3b-ae1bef387764.png">

Sometimes, on scroll, it would appear and disappear on different lines

I cannot reproduce it on the version with new icons, but I report it so that you can look at the bug if you did not fix it properly because you did not notice it (I did not have time yet to look at the code details)

Best regards

**Comment by PhilZ-cwm6** [comment]
edited with my feedback :-)

best regards

**Comment by Sentaroh** [comment]
Thank you.

New ICON.
![image](https://user-images.githubusercontent.com/4037866/95328557-ae9aa900-08e0-11eb-8bea-03384cb386d6.png)

The lack of ICON is a bug in the first version, which has been resolved in the new version.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Thank you, looks really better for me
I will compile asap and lest you know if any issues once done, or I close the issue

Best regards
