### ISSUE TITLE
Fix various bugs related to the new execute schedule buttons #184

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#185]
Pull request: https://github.com/Sentaroh/SMBSync2/pull/184

Please look at the detailed description of the pull request for a complete list of changes
This patch fixes many bugs related to the new size limit in Schedule name + the start schedule buttons
It also fixes a few bugs introduced by previous commits in the Top Sync Button for sync tasks
+ translations + bug fixes

Pictures of some of the changes:

- **Display error message properly when renaming an invalid schedule**
Before: error not displayed, regular warning in red
<img width="324" alt="Screenshot_1602144761" src="https://user-images.githubusercontent.com/2428217/95523004-dc115080-09cd-11eb-8912-d9955c2072a9.png">

**After**: properly display the error message
<img width="324" alt="Screenshot_1602193087" src="https://user-images.githubusercontent.com/2428217/95523009-dca9e700-09cd-11eb-8a77-d718625f701d.png">

- **Do not enable start schedule button for invalid schedules**
<img width="324" alt="Screenshot_1602145498" src="https://user-images.githubusercontent.com/2428217/95523189-47f3b900-09ce-11eb-8a2c-46fb00ae18e6.png">
<img width="324" alt="Screenshot_1602192967" src="https://user-images.githubusercontent.com/2428217/95523190-4924e600-09ce-11eb-93a6-bbef8973eba7.png">

- **Display error message properly when editing an invalid schedule**
<img width="324" alt="Screenshot_1602150244" src="https://user-images.githubusercontent.com/2428217/95523251-72457680-09ce-11eb-8de9-7b5b798aeafa.png">
<img width="324" alt="Screenshot_1602193175" src="https://user-images.githubusercontent.com/2428217/95523253-72de0d00-09ce-11eb-87ef-fa2d317c4127.png">

- **Detect invalid schedules because no Auto SyncTask is defined in SyncTasks Sync List**
<img width="324" alt="Screenshot_1602199677" src="https://user-images.githubusercontent.com/2428217/95523402-d10af000-09ce-11eb-92cf-a26119372538.png">
<img width="324" alt="Screenshot_1602199673" src="https://user-images.githubusercontent.com/2428217/95523405-d1a38680-09ce-11eb-88f1-f8cc8f54a1cb.png">

- **Detect schedule execution errors properly**
<img width="324" alt="Screenshot_1602193049" src="https://user-images.githubusercontent.com/2428217/95523297-8d17eb00-09ce-11eb-9550-20aec8c91b13.png">

And many others as in the detailed description

Let me know please if you find more bugs

Best regards

**Comment by PhilZ-cwm6** [comment]
Let me know please if I must rebase it because of the excel template merge. However, if you can do it, it would be great as I have less and less time these days

Best regards

**Comment by Sentaroh** [comment]
Thank you.

This time, I will do the reflection to Excel. I need to figure out what to do in the future.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Thank you,

A text csv separated by tabs or a custom separator or xml global template, then imported/exported by excel could be a solution. It is easier to edit the text file, then import/export it in excel
 
Thank you again and best regards

**Comment by Sentaroh** [comment]
Thank you.

I'm going to do some checking and merging now, so please don't update until I've completed my work (about a day).

Best regards.

**Comment by PhilZ-cwm6** [comment]
Yes, sure
Let me know if there are bugs.
I created many invalid Schedule and SyncTask cases with old versions to verify if it is ok

The only thing I was not sure about is this commit:
https://github.com/Sentaroh/SMBSync2/pull/184/commits/c1363ddc94e5f0bd3aa8864462b98cc8d6450318

I am not sure why that handler was there. Maybe an old code that is no more needed or something I missed

Best regards

**Comment by PhilZ-cwm6** [comment]
Hi,
I pushed separately the Excel and xml templates, rebased on your current branch. They can directly be applied to  my pull request
I verified after an export and the changes match perfectly

Since I know exactly the changes I did, it was fast to just copy paste the column and add my changes.

Best regards

**Comment by Sentaroh** [comment]
Hi,

Confirmation and merge completed and pushed.
Additional changes are as follows
- Change zh and ja translation
- Fixed a bug in schedule editing that prevented the Save button from being grayed out when undoing an edit.
- In the Excel file, fixed values (e.g. settings_log_level) are filled in dark gray to make it clear that no translation is required
- Change schdule list item right margin value 10dp to 5dp
- When you long tap the schedule information at the bottom of the screen, all the schedule information will be shown in a popup window.
![image](https://user-images.githubusercontent.com/4037866/95633912-a2227600-0ac3-11eb-933e-972e16a9f295.png)
Best regards.

**Comment by PhilZ-cwm6** [comment]
thank you,

> Fixed a bug in schedule editing that prevented the Save button from being grayed out when undoing an edit.

I could not figure it and I ignored it, nice catch
