### ISSUE TITLE
Schedule button size mis-match

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#186]
Hi,

Can you adjust please the schedule button like in pictures below
It is rectangular and not square like the SyncTask button

<img width="324" alt="Screenshot_1602144480" src="https://user-images.githubusercontent.com/2428217/95523559-36f77780-09cf-11eb-9623-4a3378ed6361.png">

In the sync tasks, it is a square and with a proper small space before the scroll bar for better GUI design
<img width="324" alt="Screenshot_1602144459" src="https://user-images.githubusercontent.com/2428217/95523557-35c64a80-09cf-11eb-910b-d44655a0aa90.png">

Best regards

**Comment by Sentaroh** [comment]
Hi,

ICON is created with 32x32 px, but it's not Square. The size is now specified.
![image](https://user-images.githubusercontent.com/4037866/95565660-7b305980-0a5b-11eb-8e2f-0a13b8e9deb7.png)

Best regards.

**Comment by PhilZ-cwm6** [comment]
You are right
I measured in Photoshop and the "a" and "b" distances are equal to 27 px. It was a visual effect that b > a
Probably accentuated by the scroll bar in contact with the icon background

Can you add a small margin between the button and the scroll bar on the right like in the SyncTask ? It will match the SyncTask layout and reduce the visual impression that b > a

<img width="324" alt="Screenshot_1602235697" src="https://user-images.githubusercontent.com/2428217/95567561-6637d400-0a23-11eb-8012-a0670d307011.png">

Thank you and best regards

**Comment by Sentaroh** [comment]
Change margin and padding value.
![image](https://user-images.githubusercontent.com/4037866/95579846-4a5b1f00-0a71-11eb-90a1-0b2ca993b8a9.png)
Best regards.

**Comment by PhilZ-cwm6** [comment]
Yes, really much better now
Best regards

**Comment by PhilZ-cwm6** [comment]
Sorry, I just tested and compared
The proper layout_marginRight is 5dp

With that, it matches the SyncTask button layout exactly
In SyncTask, the schedule_sync_list_sync ImageButton inherits a LinearLayout margin of 5 dp, which is not the case in in schedule

```
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginLeft="5dp"
        android:layout_marginRight="5dp" //------- this margin makes it proper
        android:layout_marginTop="5dp"
        android:orientation="horizontal" >

        <LinearLayout
            android:id="@+id/schedule_sync_list_entry_layout"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="0.5"
            android:baselineAligned="false"
            android:orientation="vertical" >
```

<img width="540" alt="Screenshot_1602246851" src="https://user-images.githubusercontent.com/2428217/95584036-53ca9400-0a3d-11eb-835a-37d299312f4e.png">



Best regards
