### ISSUE TITLE
Auto Scroll broken

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#194]
Hi,
I just noticed that one of your last commits broke the auto scroll:
- when a sync is ongoing, Messages tab does not auto scroll any more

Can you fix it ? 

Thank you and best regards

**Comment by Sentaroh** [comment]
Hi,

A fixed version has been pushed.

Best regards.

**Comment by PhilZ-cwm6** [comment]
thank you, it works now
best regards
