### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by gv74** [Sentaroh/SMBSync2#198]
Can you publish the application on F-Droid? Thank you.

**Comment by Sentaroh** [comment]
Hi,

It is published on GitHub and the APK is also available for download, so it will not be published on F-Droid.

Best regards.

**Comment by tanrak** [comment]
This superb app is now on IzzyOnDroid repo: https://apt.izzysoft.de/fdroid/

**Comment by gv74** [comment]
> It is published on GitHub and the APK is also available for download, so it will not be published on F-Droid.

OK. Thank you.

**Comment by gv74** [comment]
> This superb app is now on IzzyOnDroid repo: https://apt.izzysoft.de/fdroid/

Thank you.
