### ISSUE TITLE
[feature request] blacklist for WiFi names

### ISSUE THREAD

**Issue by DJCrashdummy** [Sentaroh/SMBSync2#201]
recently i stumbled across this app and it seems pretty cool! kudos!
thank you very much for making this FOSS... :+1: perhaps i can finally replace another proprietary piece of software at my phone.

the only feature which is IMHO lacking beside the several whitelist options is also a blacklist (e.g. to don't suck a friends limited data plan, if you are using his hotspot; to don't use your companies WiFi for whatever reason; etc.).

if this feature can be implemented, this app would be perfect! :clap:

**Comment by DJCrashdummy** [comment]
btw: is there a reason why only the *"Access point list"* option is grayed out and not select-able?

**Comment by Sentaroh** [comment]
Hi,

In order to comply with Google Play's privacy policy, we no longer use WiFi SSID names to control the WiFi SSIDs.
"Access Point List" is not available to select as it is just for compatibility purposes.

Best regards.

**Comment by JustMyGithub** [comment]
> we no longer use WiFi SSID names to control the WiFi SSIDs. "Access Point List" is not available to select as it is just for compatibility purposes.

Sorry, I do not understand this sentence. Does it mean that Google does not allow apps (on Play Store) to do "only when connected to SSID MyWifi" actions? (If so, this maybe outdated according to https://github.com/Sentaroh/SMBSync2/issues/239#issuecomment-972616294 ?) -- I am trying to figure out if I am just to stupid to find the SSID whitelist in the app or whether it was removed.

Thank you.

btw as you probably know there are alternatives like F-Droid :)
