### ISSUE TITLE
filters lack some common media formats

### ISSUE THREAD

**Issue by DJCrashdummy** [Sentaroh/SMBSync2#202]
how about adding some additional media formats to the default filters? at least opus, m3u8, mkv and webm... if you don't mind i've compiled a list of (more and less common) formats/extensions, which are missing.

**audio files:** `*.opus`; `*.spx` (Speex); `*.oga`, `*.ogm` (2 not so common ogg extensoins); `*.mka` (Matroska-audio); `*.m4b` (mp4-audiobooks)
**playlists:** `*.m3u8` (utf8-variant of m3u); `*.xspf` (spiff: XML Shareable Playlist Format); `*.pls` (ini-playlist)
**images:** `*.jfif`, `*.jif`, `*.jfi` (3 not so common jpeg extensions like *.jpe); `*.svgz` (compressed svg)
**videos:** `*.mkv` (Matroska); `*.webm`; `*.m4v` (not so common mp4-video extension)

**Comment by Sentaroh** [comment]
Hi,

I don't want to register an extension that is not in common use, as it would confuse the user.
If you want to select an extension other than the preset one, you can add a "File filter".

Best regards.
