### ISSUE TITLE
Cannot Create Directory

### ISSUE THREAD

**Issue by JustOtterGuy** [Sentaroh/SMBSync2#203]
Hello,
Im trying to sync my SD to a smb server in a new Samsung A51 mobile (Android 10). I'm using the Copy mode.
Appsync2 does very well the job, unless an issue; the sync crashes over and over again when the app has to create a new directory in the smb server (if I create the directory from a PC, the app just  works fine).
The error message is: can't create the file when already exist (and no, the directory doesn't exist previously).

**Comment by Sentaroh** [comment]
Hi,

Would you please send me a log in accordance with the link below?
https://drive.google.com/file/d/1G8ZYi_RoUi4oafJRynA96Li0dkXQiGAh/view?usp=sharing
1.Enable logging by above pdf step1-4.
2.Perform sync fore reproduce error.
3.Send a log by above PDF step 6 to 14.

Best regards.

**Comment by JustOtterGuy** [comment]
Ive attached the log throught mail. 
Thanks!

**Comment by Sentaroh** [comment]
Hi,

I think it's a problem on the SMB server side.
>Cannot create a file when that file already exists. 
>NT Status=0xc0000035 

Please review the settings of your SMB server.

Best regards.
