### ISSUE TITLE
UUID List Changes Confirmation bug

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#207]
How to reproduce:
- Edit UUID list
- instead of using the button Cancel, use the "Device Back Button"
- No confirmation menu is displayed unlike the other menu options in the app

When using Cancel button, the prompt to confirm exit without saving changes is properly displayed

Best regards

**Comment by Sentaroh** [comment]
Thank you for you testing.

Fixed version has been pushed.

Best regards.

**Comment by PhilZ-cwm6** [comment]
it works properly now, thank you
best regards
