### ISSUE TITLE
Import Tasks from different device: user name/pass hash

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#215]
Hi,

I noticed an issue in recent builds, when you import a task list from a different device
If a task has smb server with user/pass, instead of detecting the signature mismatch and setting the Task to Error State, the user name and password are filled with the hash string

Previously, the prompt message was properly displayed warning that the user/pass could not be imported and the task was set to error

Best regards

**Comment by Sentaroh** [comment]
Hi,

When importing Auto save files from other phones with "Select another file", it is assumed that there are only two types of files: "All encrypted" or "No encryption", so there is no error.

When importing a file with the file extension "stf", it is now considered an "Auto save" file.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Hi
>
> When importing a file with the file extension "stf", it is now considered an "Auto save" file.
> 

Your last commit https://github.com/Sentaroh/SMBSync2/commit/9d7638b3cd8b19ae4396c4c3262faa5989a6b164 properly fixed my issue when manually importing autosaved files. Now it acts as expected 👍 

Best regards
