### ISSUE TITLE
Fix size filter defaults

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#226]
Hi,
Refer to: https://github.com/Sentaroh/SMBSync2/pull/225

I really think the default size value must be 0 for both greater than and less than values and not 0 or 1 internally on a corrupted settings file !
Also, the last change you added will loose the last size value set by the user if he disables the file filter and restarts the app ! Other app settings do not behave like this normally and are properly saved when a setting option is enabled/disabled.

I think that this change is more simple to manage, fixes the bug resetting the size value on app restart mentioned above and do not use internal 1 default value on a corrupted settings file while the real default on app start is 0

The commit should not conflict with the ongoing notifications test branch

Thank you and best regards

**Comment by Sentaroh** [comment]
Hi,

The reason why the omit value was set to 1 when the file size filter was "Greater than" was to avoid conflicts with the "Ignore empty files (0 Bytes size)" option.

I would like to change the default value of the file size filter as follows
1. Set the default value to 0
2. show a warning when the "Ignore empty files (0 Bytes size)" option is enabled when the file size filter is "Greater than 0".
3. display a warning when the file size filter is set to "Greater than 0" when the "Ignore empty files (0 Bytes size)" option is enabled

Best regards.

**Comment by Sentaroh** [comment]
Hi,

Merged your changes and changed the Japanese notation.

Best regards.

**Comment by PhilZ-cwm6** [comment]
Hi,

I get your idea.
However, personally, I don't see it as a problem:
- The "Ignore empty files" option is in Advanced menu and unchecked by default
- The Filter Size Value doesn't accept the value of 0
- If we set to 1, it can be 1KB, 1MB... so "Less than" still handles some files between 0 and the 1KB set value for example

Again, adding many warnings can be annoying since we cannot check a "Never warn again about this..." option or it will make the settings more complex if you do so.
So, in my opinion, a warning is not needed because it is not a risky setting.

But anyway, thank you again for the follow up and best regards
