### ISSUE TITLE
File size filter valid values

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#228]
Hi,
The last commit: https://github.com/Sentaroh/SMBSync2/commit/4e6d5a1dbb2f9ef2d70ff0173139a18ee7cc35c3
has an issue: it doesn't properly validate the sanity of the settings from a potential corrupted file
This would allow enabling the size filter and setting the value to 0 on app load, which is not allowed in the app settings

Maybe just modify the "debug message" to not warn if the "Size Filter" is disabled AND "size value" equals 0 because it is not an exception. However, all other cases should display the warning

What do you think ?

Edit: also, on the released 2.49 version, it should never be 0 in the settings file on app load, except if the settings were corrupted, so the warning should be valid in all cases !

Best regards

**Comment by Sentaroh** [comment]
Hi,

Since the current method cannot prevent malicious changes to the task list, let's use a method that allows "0".

Best regards.
