### ISSUE TITLE
From version 2.46 not possible backup from SD card

### ISSUE THREAD

**Issue by dremn** [Sentaroh/SMBSync2#229]
Hello,

I was using 2.45 until last week, then install update 2.49 - problem with SD card, tried to 2.47, same problem, still alert SD card is no mounted. But SD card working fine for another application.
I was installed again 2.45 and its OK, SD card available....
Android 6.0.1

Im posting just for info... I dont have time to trying and tested. 2.45 working fine so I will using this one... Anyway thank you for this app its really great and I hope you will fix issue with SD card.

**Comment by Sentaroh** [comment]
Hi,

Please send us the "System Info" of Ver2.45 and Ver2.49. Or, please paste the contents of "System Info".
![image](https://user-images.githubusercontent.com/4037866/108786893-00a24980-75b8-11eb-91e7-f698897b5f68.png)
![image](https://user-images.githubusercontent.com/4037866/108787145-7e665500-75b8-11eb-8aa4-c4bb2bcd654d.png)

Best regards.
