### ISSUE TITLE
[BUG] Lost Tasks

### ISSUE THREAD

**Issue by fritz-net** [Sentaroh/SMBSync2#230]
I don't know why or how it happend, but my task list is empty. However the Schedules are there (complaining that tasks are missing).
I did not change anything in the app since long (only triggered manual syncs)

The last sync failled cause of no wifi

**Comment by Sentaroh** [comment]
Hi,

Are you using tools such as "Titanium Backup" to backup and restore?
SMBSync2 uses Android Key Store, so if you use tools such as "Titanium Backup" to backup and restore, it will not restore properly.

Best regards.

**Comment by fritz-net** [comment]
@Sentaroh Thanks for the fast response.

I did not restore anything. (I also did not make a export of the settings :( so I had/have to reconfigure it) I was justing using it in the Background and today, when I wanted to trigger manual sync, I saw that my tasks are missing (my last synced files were from 7. March so this is likely the date when it stopped).

Since I can't reproduce it I know that you can't do anything about it, I just wanted to report it so you know that there is or could be an issue.

Currently I have Version 2.47 (I don't know if an update happend) on Android 9

best regards

**Comment by fritz-net** [comment]
Note: I had this issue again, but this time I realized that you implemented automatic backups of the configs. I could restore the settings from there. ( I think I used the same old version when the issue occurred again - now I updated the app)
