### ISSUE TITLE
Sync task stops suddendly

### ISSUE THREAD

**Issue by stefano-sb** [Sentaroh/SMBSync2#233]
Hi, in my Android TV Box (Beelink GT-King with Adroid 9) the tasks that need to synchronize a lot of files (eg 20,000) stop running suddenly after a few minutes without having finished and without errors or messages in the log. If it can be useful to analize the problem inside the logcat I found this message 

"04-06 13: 54: 59.135 I / ActivityManager (3784): Killing 26619: com.sentaroh.android.SMBSync2 / u0a57 (adj 0 ): Too many Binders sent to SYSTEM "

I have already tried to exclude the app from "optimize battery" but without success. 

Thanks

**Comment by Sentaroh** [comment]
Hi,

Sorry for late response.

"Too many Binders sent to SYSTEM" seems to occur when I do a lot of MediaScanner in a short time.
As a solution, we changed the MediaScan method from Static calls to calls from MediaScannerConnectionClient.
https://github.com/Sentaroh/SMBSync2/commit/3eb43db7f5ec04d97f65a9309fbcfee2b52f8dd0

Please install and test the application from the link below.

[SMBSync2_2.52_284_release_test_01.apk.zip](https://github.com/Sentaroh/SMBSync2/files/6294679/SMBSync2_2.52_284_release_test_01.apk.zip)

Best regards.

**Comment by stefano-sb** [comment]
Hi, thanks for the answer. This version works perfectly! If do you need other check I am here!

Thank you!!

Stefano

**Comment by Sentaroh** [comment]
Hi,

We will be releasing this change to Google Play in a week, so please continue to use it.

Best regards.
