### ISSUE TITLE
Can't find the option to start syncing from the Tasker

### ISSUE THREAD

**Issue by leranp** [Sentaroh/SMBSync2#234]
I have read that there is an option to start the sync from the Tasker, but i didn't found this option.
Can someone please help me to find?

**Comment by Sentaroh** [comment]
Hi,

Please refer to the PDF ("5.1.1. Example for Tasker") in the link below to configure Tasker.
https://drive.google.com/file/d/0B77t0XpnNT7OYzZ0U01rR0VRMlk/view?usp=sharing

Best regards.

**Comment by leranp** [comment]
Thank you @Sentaroh
