### ISSUE TITLE
Edit the file name with * 

### ISSUE THREAD

**Issue by leranp** [Sentaroh/SMBSync2#235]
Hi,
My samsung s10+ call Recorder is recording to file name with the number of the conversation, but in my country we have numbers that start with * , when i tried to sync file with the charts the app doesn't success to edit the file name.
Is there any workaround for thia issue?
This is the log file:
```
E 2021/04/10 21:31:16.819 SyncThread       Call Recorder Files: /storage/emulated/0/Call/Call recording *8860_200114_093427.m4a The source file or directory name contains invalid characters for the destination. Edit name to allow sync. Character=* [Sync Failed]
```

**Comment by Sentaroh** [comment]
Hi,

The characters that can be used in the file name / Directory name differ depending on the File System. You can use non-null characters in internal storage, but you cannot use ":, \, *,?,", <,>, |" characters in external storage (FAT32 / exFAT) and SMB servers.

Workarounds are
1. Remove or convert the unavailable characters from the file name.
2. Optionally exclude files/directories
![image](https://user-images.githubusercontent.com/4037866/115141917-d3cf5780-a079-11eb-96d3-9e70d7cac8aa.png)

Best regards.
