### ISSUE TITLE
[Feature request] skip files and directories with long name

### ISSUE THREAD

**Issue by blubblwubbl** [Sentaroh/SMBSync2#241]
Hi

I tried this app and it looks really helpful, thanks for the development so far.
I tried to sync from my android to my NAS (Synology DS220j). This uses eCryptFs for the encryption, which restricts the filename length to 143, and Synology seems to restrict this further to 130 characters. With 131 characters I get the error: The filename, directory name, or volume label syntax is incorrect.)

Could you add a funtionality similar to the  "skip directory and file names that contain invalid characters (",:,\,*,<,>,|)" option, to skip directory and file names with more than 130 (or variable number of) characters?
Alternatively the option to sync to a .zip file via smb would work as well I would guess.

If I missed an exisisting method to work around this, I would be glad to hear about it.

**Comment by Sentaroh** [comment]
Hi,

Sorry for late response.

Add an option to ignore the file if the length of the file name is longer than the specified value. Please wait for about a week while we create a test APK.

Best regards.

**Comment by Sentaroh** [comment]
Hi,

The option "Ignore files with file names longer than specified length" has been added, so please install and check it.
![image](https://user-images.githubusercontent.com/4037866/121433612-36c4d700-c9b7-11eb-93aa-3e7bee4fbe89.png)

Please note that the APK is signed with the same signature key as the Google Play Version.

[SMBSync2_2.53_285_release_test_01.apk.zip](https://github.com/Sentaroh/SMBSync2/files/6627063/SMBSync2_2.53_285_release_test_01.apk.zip)

**Comment by blubblwubbl** [comment]
Hi,
I tried the apk. Unfortunately it looks like it does not only skip the file but stop the whole sync process after the first file to skip and the rest of the files is not synced
![Screenshot](https://user-images.githubusercontent.com/73914326/121813639-30f81b80-cc6d-11eb-8fbc-7ea7d16435db.png)

**Comment by Sentaroh** [comment]
Hi,

Fixed a bug that caused processing to stop.

[SMBSync2_2.53_285_release_test_02.apk.zip](https://github.com/Sentaroh/SMBSync2/files/6645230/SMBSync2_2.53_285_release_test_02.apk.zip)

Best regards.

**Comment by blubblwubbl** [comment]
Thank you for implementing the feature, it works great now.

**Comment by Sentaroh** [comment]
Hi,

Version 2.53 released to GooglePlay.

Best regards.

**Comment by Sentaroh** [comment]
Closed.
