### ISSUE TITLE
Access SMBSync2 with Automate

### ISSUE THREAD

**Issue by EfficiencyVI** [Sentaroh/SMBSync2#245]
Hi,

the manual says, there is a tasker api. So it should be possible to access it with [Automate](https://play.google.com/store/apps/details?id=com.llamalab.automate) too. But there is no plugin for SMBSync2 listed. Is there a workaround or something I'm doing wrong?

**Comment by Sentaroh** [comment]
Hi,

SMBSync2 starts synchronization upon receiving Intent from Tasker, so no Plugin is required.

The following is an example of Tasker definition, and you can change prof1/prof2 according to your environment.
![image](https://user-images.githubusercontent.com/4037866/123531339-c18b2d00-d73e-11eb-98b0-51840ce01ac0.png)
Action:com.sentaroh.android.SMBSync2.ACTION_START_STNC
Extra: SyncProfile:”prof1, prof2”
Target:	Activity

Best regards.

**Comment by EfficiencyVI** [comment]
Thank you. Seems, I will have to use Foldersync then.
