### ISSUE TITLE
Zip compression alignment in large layout

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#71]
There is still an alignment issue in Russian or long languages if one of the radio buttons has a 2 lines text or more.

Landscape/Large Russian Layout:
<img width="324" alt="Screenshot_1589284084" src="https://user-images.githubusercontent.com/2428217/81697570-6aa49480-9465-11ea-9619-0f04bb3d97d8.png">

In edit_sync_folder_dlg_zip.xml, replacing android:gravity="center_vertical" in RadioGroup by "Top" fixes it but less nice looking for most one line languages

I couldn't find any simple clue to fix it

**Comment by Sentaroh** [comment]
I'm going to change it to Spinner.

**Comment by PhilZ-cwm6** [comment]
good idea :-)
