### ISSUE TITLE
Rotation visual only one left bug to fix

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#77]
Thank you a lot, last commit fixed all functional bugs due to rotation.
I found a few more **visual only** bugs. Functionality is preserved, so really not a big issue in reliability of sync edit. All are fixed by my last commit except :

This one needs to save/restore the browsing path view
- **Edit master/target folder rotation: enable rotation and List Folders visual bug**
This includes the way to enable rotation in edit master/target folders
  * phone in portrait mode
  * click to edit an existing task with master as Internal Storage
  * turn phone in landscape mode
  * click master folder (1)
  * List Directories
  * select a subdirectory
  * back to portrait mode
  * the proper directory is selected (.../Android/obb/ in my example) but the folders view is always back to root of master
  * the bug is only visual because when you click Ok, the proper Android/obb folder is selected
  also, all menus are perfectly saved/restored on rotation

**(1)** **When entering Tagert/master folders edit dialog in portrait, we can no rotate.
  This exact step enables rotation into the edit master folder view**

<img width="672" alt="Screenshot_1589445192" src="https://user-images.githubusercontent.com/2428217/81917510-90e94200-95d5-11ea-9ed6-9426dab8e7cc.png">
<img width="324" alt="Screenshot_1589445120" src="https://user-images.githubusercontent.com/2428217/81917511-9181d880-95d5-11ea-8c80-dc356c049053.png">

- **~~Edit master/target folder rotation in Archive mode: layout gap and file types gone visual bug~~**

  * ~~Archive mode~~
  * ~~enable rotation in target folder edit view like in first step (1)~~
  * ~~back to portrait~~
  * ~~A long gap is created to access "Only files with following extensions will be archived..."
  we need to scroll down to see the options~~
  * ~~the file extensions are no longer displayed (reveals bug in landscape display on small devices)~~
  * ~~the bug is only visual because all menus are perfectly saved/restored on rotation~~

**This one is fixed by this commit: https://github.com/Sentaroh/SMBSync2/pull/78**

<img width="324" alt="Screenshot_1589445837" src="https://user-images.githubusercontent.com/2428217/81917321-57b0d200-95d5-11ea-942a-b52024ef255f.png">
<img width="324" alt="Screenshot_1589445852" src="https://user-images.githubusercontent.com/2428217/81917324-58496880-95d5-11ea-8524-40fc1e117dc8.png">
<img width="400" alt="Screenshot_1589447724" src="https://user-images.githubusercontent.com/2428217/81917327-58e1ff00-95d5-11ea-8404-83c3fdbd39ea.png">

**Comment by PhilZ-cwm6** [comment]
I would really appreciate that you enable back rotation in Edit master/target folder instead of blocking my way to access it
The visual issues above are minor and could be fixed I guess. After that, the rotation mode will be perfectly working in Edit master/target folders

Thank you for the quick follow-up

**Comment by PhilZ-cwm6** [comment]
I edit my issue
All were fixed in this commit: https://github.com/Sentaroh/SMBSync2/pull/78

Even the last one is fixed now by the commit
**Remains only the first issue to save/restore browsing path**

After that, the rotation mode will be perfectly working in Edit master/target folders.
It would really be great that you enable back rotation in Edit master/target folder instead of blocking my way to access it.

Thank you for the quick follow-up

**Comment by Sentaroh** [comment]
Thank you.

1.Fixed a bug where the list of files displayed when the screen is rotated would return to the default value.(Utilities/CommonFileSelector.java)
2.Fixed a bug where fixScreenOrientation() didn't work on Landscapes.

**Comment by PhilZ-cwm6** [comment]
Thank you,
The Utilities lib update works perfectly
Can you revert the rotation block ? Everything works perfectly now

**Comment by Sentaroh** [comment]
Supported reloading the Layout when the screen is rotated when editing SyncFolder. (remove fix/unfix function)
