### ISSUE TITLE
Same target/master combination

### ISSUE THREAD

**Issue by PhilZ-cwm6** [Sentaroh/SMBSync2#85]
1.  **Same master/target combination issues**
The last change in checkMasterTargetCombination() makes this combination possible:

Case master or target are ""
<img width="324" alt="Screenshot_1589626807" src="https://user-images.githubusercontent.com/2428217/82118122-5f0ee180-9775-11ea-9839-bd5fce9bccba.png">

2. **Note: the check wasn't perfect either before the change**: case target AND master are not ""

- **with the include filter: target and master are the same**

<img width="324" alt="Screenshot_1589626468" src="https://user-images.githubusercontent.com/2428217/82118037-c2e4da80-9774-11ea-918c-5d67589e6dd8.png">

- **target is included in master case**: no filter selected

<img width="324" alt="Screenshot_1589627122" src="https://user-images.githubusercontent.com/2428217/82118226-03912380-9776-11ea-9d91-20f269facc4f.png">

All these combinations should be invalid

**Comment by PhilZ-cwm6** [comment]
will test and give feedback asap

**Comment by PhilZ-cwm6** [comment]
Well, the filter is still not working as expected. Exp. of not possible things:

- I want to exclude all /cache/ paths and not only a specific /specific_path/cache
- wildcards not implemented in dir filter
- example in images:
master: /internal_storage/download
target: /sdcard/temp
exclude directory filter: cache

result: "/temp/cache", "\_cache", "cache\_" and "my_cachemir_shirt" are copied. It is ok if we consider exact match from root of master, but not what I expected. I also tried exclude wildcards such as \*/cache/\* and they don't work.

Each path must be exactly specified, one by one

<img width="324" alt="Screenshot_1589739697" src="https://user-images.githubusercontent.com/2428217/82156681-f874eb00-987c-11ea-814d-b98910e1b718.png">

![Untitled](https://user-images.githubusercontent.com/2428217/82156646-a0d67f80-987c-11ea-8d91-8efbf148f7c2.jpg)

**What do you think about this way of logic to proceed:**
1. target cannot be a sub-directory of master (target included in master): works perfectly actually

2. no need to check if exclude/include filters can cause the target become under master (because filter applies to master as root)
exp:
master= /sdcard/download/master
target= /sdcard/download/target
folder exclude filter: master

The exclude filter will exclude /sdcard/download/master/master and not /sdcard/download/master
so no need to check it and it is user responsibility

3. filter only applies to master: ~~works ok currently~~ **edit: applies to both target and master currently**. This is important mainly in Mirror mode to keep target as a real mirror and always delete not matching files on target. Maybe a warning is needed or just a mention that filter is set to apply in master, that is files to be copied

4. if filter is "dir_name" == "*/dir_name/": will match exact name **under any path**: 
  + /sdcard/download/master/dir_name
  + /sdcard/download/master/any_folder/dir_name
  + not matching: a folder named "my_dir_name"

5. if filter is "/dir_name/" == "/dir_name": will match only if in root of master
  + /sdcard/download/master/dir_name
  + not match: /sdcard/download/master/any_folder/dir_name

6. optional: asterix (\*) wildcards support
  + "\*dir_name\*" or "\*dir_name" or "dir_name\*"
  + we can block wildcards inside the name to simplify: "\*dir_n\*me" not allowed: invalid character in file/dir name, asterix wildcard only accepted at begin/end

that way, we can exclude things like:
  + thumbnails == \*/thumbnails/\*
  + cache == \*/cache/\*
  + /cache == cache folder in root of master

7. in the main view, we cannot say if an entry is include or exclude: maybe it is better to show them differently (color? a +/- sign, different lines with an exclude/include title...)

Let me know if you would like me to look at a proper code or you do it ?

**Comment by PhilZ-cwm6** [comment]
done editing and escaping the asterix and underscores in my comment examples

**Comment by PhilZ-cwm6** [comment]
another edit to escape asterix and clarify reasoning. Most sync programs work this way with wildcards
starting with "/" signifies the root of master, no starting "/" is anywhere and exact match

**A last note: in the main view, we cannot say if an entry is include or exclude: maybe it is better to show them differently (color? a +/- sign, different lines with an exclude/include title...)**

**Comment by PhilZ-cwm6** [comment]
edit: point 3 because actually after testing, filter applies to master and target

**Comment by PhilZ-cwm6** [comment]
pushed a commit which fixes exclude filters to be more flexible
Hope you can look at it or start with it for enhancements

**Comment by Sentaroh** [comment]
Sorry for late response.

> target cannot be a sub-directory of master (target included in master): works perfectly actually

Master is "" root directory(/storage/emulated/0)
Target is "target"(/storage/emulated/0/target)
Filter is "dir"
Sync From "/storage/emulated/0/dir" to "/storage/emulated/0/target/dir"

If you want to specify only the Directory name, please specify it like "////cache".
![図1](https://user-images.githubusercontent.com/4037866/82407459-2ab46180-9aa4-11ea-9bb5-acf820f57e43.png)
![図1](https://user-images.githubusercontent.com/4037866/82407560-6a7b4900-9aa4-11ea-9602-1c4406d8405a.png)

Best regards.

**Comment by Sentaroh** [comment]
> 4.if filter is "dir_name" == "*/dir_name/": will match exact name under any path:

Use "\\\\" because it overlaps with the current implementation.
- "*/cache" matches "/master/test/cache"
- "*/cache/*" matches "/master/test/cache/any"

>6.optional: asterix (*) wildcards support "*dir_n*me" not allowed:

The current implementation allows it, so it can't be banned.

**Comment by PhilZ-cwm6** [comment]
I continue in the pull request
